<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\InfraDocs.Shared\InfraDocs.Shared.csproj" />
    <ProjectReference Include="..\InfraDocs.Application\InfraDocs.Application.csproj" />
    <ProjectReference Include="..\InfraDocs.Domain\InfraDocs.Domain.csproj" />
    <ProjectReference Include="..\InfraDocs.Infrastructure\InfraDocs.Infrastructure.csproj" />
  </ItemGroup>

</Project>
